name: Deploy static content to Tencent COS

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: cos
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and setup coscmd
        run: |
          pip install -U coscmd
          coscmd config -a '${{ secrets.COS_SECRETID }}' -s '${{ secrets.COS_SECRETKEY }}' -b '${{ secrets.COS_BUCKET }}' -r '${{ secrets.COS_REGION }}'

      - name: Generate static content
        run: |
          npm install
          npm run build

      - name: Deploy to COS
        run: |
          coscmd upload -rs --delete public/ /
