name: Deploy static content to Tencent COS

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: cos
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download and setup coscli
        run: |
          wget -nv -O coscli https://github.com/tencentyun/coscli/releases/latest/download/coscli-linux
          chmod a+x coscli
          touch ~/.cos.yaml
          ./coscli config set --secret_id '${{ secrets.COS_SECRETID }}' --secret_key '${{ secrets.COS_SECRETKEY }}'
          ./coscli config add --alias sinosky --bucket '${{ secrets.COS_BUCKET }}' --region '${{ secrets.COS_REGION }}'

      - name: Generate static content
        run: |
          npm install
          npm run build

      - name: Deploy to COS
        run: |
          ./coscli sync public/ cos://sinosky/ --recursive
